FROM node:20.12.0-alpine3.19

WORKDIR /app

COPY package.json package-lock.json tsconfig.json turbo.json ./

RUN npm install

COPY . .

RUN npm install

RUN npm run db:generate

CMD [ "npm", "run", "start-user-app" ]
