name: Build success on PR

on:
    pull_request:
        branches: -master

jobs:
    build:
        name: Build the project
        runs-on: ubuntu-latest
        steps:
            -uses: action/checkout@v3
            -name: Use Node.js
             uses: action/setup-node@v3
             with:
                node-version: "20"
            
            -name: Install dependencies
             run: npm install
            
            -name: Generate prisma client
             run: cd packages/db && npx prisma generate && cd ../..

            -name: Run Build
             run: npm run build
